version: '3.8'

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: tron-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: tron-backend
    networks:
      - dev
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: tron-frontend
    networks:
      - dev
    restart: unless-stopped
    