version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: tron_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    conteiner_name: tron_backend
    ports:
      - "8000:8000"
    enviroment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app 
