services:
  frontend:
    build: ./frontend
    container_name: tron-frontend
    expose:
      - "3000"
    networks:
      - web

  backend:
    build: ./backend
    container_name: tron-backend
    expose:
      - "8000"
    networks:
      - deweb
  nginx:
    image: nginx:alpine
    container_name: tron_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cerbot/www:var/www/cerbot
      - ./cerbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - web

  
  certbot:
    image: certbot/certbot
    container_name: tron_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ""
    command: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      -- email $EMAIL --agree-tos --no-eff-email
      -d $DOMAIN"

networks:
  web:
    driver: bridge
