FROM node:alpine as build

COPY package.json package.json
RUN npm install
COPY . .
node server.js

FROM nginx:stable-alpine

COPY --from=build /dist /usr/share/nginx/html
COPY --from=build nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8000
CMD [ "nginx", "-g", "daemon off;" ]
